batch_size: 512
clipping: 10
curvature: 10
device: cuda
hid_chnl: 64
in_chnl: 2
iteration: 10000
key_size_embd: 64
key_size_policy: 64
lr: 0.0001
n_agent: 4
n_worker: 8
seed: 1
test_node_n: 51
train_node_n_max: 50
train_node_n_min: 10
val_size: 64
validation_data_size: 512
